### ISSUE TITLE
Why the 7 secs delay?

### ISSUE THREAD

**Issue by xinstein** [Kevin-De-Koninck/PleaseSleep#1]
I know you must have had your reason, can you tell me about it? I'm just curious

**Comment by Kevin-De-Koninck** [comment]
I’ve added this delay because I want to wait until the system is fully woken up from a hibernate sleep. If we don’t wait a couple of seconds, there’s a small chance that the system would freeze as soon as the script enables Airport again.

**Comment by xinstein** [comment]
Thank you for the explanation~
